version: '3.8'

services:
  telegram-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - XAI_API_KEY=${XAI_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - EMBEDDING_SERVICE=${EMBEDDING_SERVICE:-huggingface}
      - LOG_LEVEL=DEBUG
    volumes:
      - ./:/app
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    env_file:
      - .env
    networks:
      - telegram-bot-network
    # Override command for development with auto-reload
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

networks:
  telegram-bot-network:
    driver: bridge
