version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - XAI_API_KEY=${XAI_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - EMBEDDING_SERVICE=${EMBEDDING_SERVICE:-huggingface}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOGS_DIR=/app/logs
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - telegram_bot_data:/app/data
    env_file:
      - .env
    networks:
      - telegram-bot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-express:
    image: mongo-express:latest
    container_name: telegram-bot-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=aegorshev
      - ME_CONFIG_MONGODB_ADMINPASSWORD=vbu677776A.
      - ME_CONFIG_MONGODB_URL=mongodb+srv://aegorshev:vbu677776A.@cluster0.c2qsjcq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    networks:
      - telegram-bot-network

volumes:
  telegram_bot_data:

networks:
  telegram-bot-network:
    driver: bridge
